### ISSUE TITLE
Log timestamps

### ISSUE THREAD

**Issue by JelleVos1** [JelleVos1/sdl-game-engine#16]
**Describe the solution you'd like**
It would be nice if logs in the log_utils namespace had timestamps.

**Comment by ShantanuBalse** [comment]
I can work on this but this'll be my first open source contribution so do let me know if there's anything I can do differently.
I'm thinking after having timestamps, the logged message could look something like this:

`[10:55:20 SUCCESS] Test success`

What do you think?

**Comment by JelleVos1** [comment]
> 
> 
> I can work on this but this'll be my first open source contribution so do let me know if there's anything I can do differently.
> I'm thinking after having timestamps, the logged message could look something like this:
> 
> `[10:55:20 SUCCESS] Test success`
> 
> What do you think?

This is perfect, awesome. I will assign you to the issue.

**Comment by JelleVos1** [comment]
Thank you so much for the contribution! If you ever want to contribute to other issues too you can just ask in the issue. I will keep adding more issues.

**Comment by ShantanuBalse** [comment]
Thanks a lot 😃
